const products = [
  {
    id: "unseen",
    name: "Dopahr Unseen Sunscreen SPF 50",
    tagline: "The original 100% invisible, weightless sunscreen.",
    price: 38.00,
    rating: 4.8,
    reviewsCount: 1240,
    type: "Lotion & Moisturizer",
    category: "Face & Lip",
    spf: 50,
    isBestseller: true,
    isNew: false,
    isMineral: false,
    image: "assets/images/unseen_sunscreen.jpg",
    description: "Dopahr Unseen Sunscreen SPF 50 is a totally invisible, weightless, scentless daily primer and sunscreen that leaves a soft, velvety finish. Perfect for all skin types, it controls shine and prepares your skin for makeup application while offering broad-spectrum protection.",
    ingredients: "Active Ingredients: Avobenzone 3%, Homosalate 8%, Octisalate 5%, Octocrylene 4%.\nInactive Ingredients: Isododecane, Dimethicone Crosspolymer, Silica, Meadowfoam Estolide, Polyester-8, Coco-Caprylate, Shea Butter, Jojoba Esters.",
    benefits: [
      "100% invisible on all skin tones—no white cast ever",
      "Weightless, scentless formula with a velvety finish",
      "Acts as a makeup-gripping primer for long-lasting wear",
      "Oil-free formula controls shine throughout the day"
    ],
    howToUse: "Apply generously and evenly as the last step in your skincare routine and before makeup. Reapply at least every 2 hours, or after 80 minutes of swimming or sweating."
  },
  {
    id: "glow",
    name: "Dopahr Glowscreen SPF 40",
    tagline: "Dewy, hydrated glow with daily sun protection.",
    price: 38.00,
    rating: 4.7,
    reviewsCount: 980,
    type: "Oil & Serum",
    category: "Face & Lip",
    spf: 40,
    isBestseller: true,
    isNew: true,
    isMineral: false,
    image: "assets/images/glowscreen.jpg",
    description: "Dopahr Glowscreen SPF 40 is a multitasking sunscreen that offers daily UV protection while giving skin an instant, dewy glow. Infused with hyaluronic acid, niacinamide, and vitamin B5, it hydrates, primes, and illuminates your complexion for a lit-from-within look.",
    ingredients: "Active Ingredients: Avobenzone 3%, Octisalate 5%, Octocrylene 10%.\nInactive Ingredients: Water, Glycerin, Propanediol, Hyaluronic Acid, Niacinamide, Panthenol (Vitamin B5), Mica, Titanium Dioxide, Iron Oxides.",
    benefits: [
      "Instant, luminous dewy finish that brightens skin",
      "Deeply hydrates skin with Hyaluronic Acid & Vitamin B5",
      "Evens out skin tone and texture with Niacinamide",
      "Can be worn alone or under makeup as an illuminating primer"
    ],
    howToUse: "Apply generously and evenly as the last step in your skincare routine. Wear it alone for a natural glow, or under makeup as a radiant primer. Reapply every 2 hours."
  },
  {
    id: "play-lotion",
    name: "Dopahr PLAY Everyday Lotion SPF 50",
    tagline: "Hydrating, water-resistant protection for face & body.",
    price: 34.00,
    rating: 4.9,
    reviewsCount: 2150,
    type: "Lotion & Moisturizer",
    category: "Body",
    spf: 50,
    isBestseller: true,
    isNew: false,
    isMineral: false,
    image: "assets/images/play_lotion.jpg",
    description: "Dopahr PLAY Everyday Lotion SPF 50 is a fast-absorbing, water- and sweat-resistant daily sunscreen for face and body. Packed with nourishing extracts of sunflower and rosemary, this non-greasy formula locks in hydration and guards against dryness and environmental stressors.",
    ingredients: "Active Ingredients: Avobenzone 3%, Homosalate 10%, Octisalate 5%, Octocrylene 10%.\nInactive Ingredients: Water, Polyester-8, Glycerin, Sunflower Seed Oil, Rosemary Leaf Extract, Cetearyl Alcohol, Caprylyl Glycol.",
    benefits: [
      "Broad-spectrum SPF 50 protection for face and body",
      "Up to 80 minutes of water and sweat resistance",
      "Hydrating formula with a clean, light fragrance",
      "Absorbs quickly without sticky residue or white cast"
    ],
    howToUse: "Apply generously to face and body at least 15 minutes before sun exposure. Reapply after 80 minutes of swimming or sweating, immediately after towel drying, and at least every 2 hours."
  },
  {
    id: "body-mist",
    name: "Dopahr PLAY Antioxidant Body Mist SPF 50",
    tagline: "Refreshing, quick-dry sunscreen mist with Vitamin C.",
    price: 21.00,
    rating: 4.6,
    reviewsCount: 730,
    type: "Spray",
    category: "Body",
    spf: 50,
    isBestseller: true,
    isNew: false,
    isMineral: false,
    image: "assets/images/body_mist.jpg",
    description: "Dopahr PLAY Antioxidant Body Mist SPF 50 is a non-aerosol, quick-drying sunscreen spray that makes full-body sun protection a breeze. Formulated with antioxidant-rich Vitamin C and green tea extract, it neutralizes free radicals while leaving skin refreshed and radiantly protected.",
    ingredients: "Active Ingredients: Avobenzone 3%, Homosalate 10%, Octisalate 5%, Octocrylene 10%.\nInactive Ingredients: Alcohol Denat., Vitamin C (Ascorbyl Palmitate), Green Tea Leaf Extract, Diisopropyl Sebacate, Fragrance.",
    benefits: [
      "Non-aerosol, continuous spray works at any angle",
      "Enriched with Vitamin C to fight environmental damage",
      "Ultra-lightweight, quick-dry formula with no greasy feel",
      "Water and sweat resistant for up to 80 minutes"
    ],
    howToUse: "Spray generously and spread evenly by hand 15 minutes before sun exposure. Hold can 4-6 inches from the skin. Do not spray directly into face—spray on hands first then apply. Reapply every 2 hours."
  },
  {
    id: "mattescreen",
    name: "Dopahr Mineral Mattescreen SPF 40",
    tagline: "100% mineral protection with a soft-focus matte finish.",
    price: 38.00,
    rating: 4.5,
    reviewsCount: 540,
    type: "Mineral",
    category: "Face & Lip",
    spf: 40,
    isBestseller: false,
    isNew: true,
    isMineral: true,
    image: "assets/images/unseen_sunscreen.jpg",
    description: "Dopahr Mineral Mattescreen SPF 40 is a dermatologist-tested, 100% mineral daily sunscreen that delivers a smooth, matte finish. Formulated with wild butterfly ginger to help filter blue light, this tinted mineral formula minimizes the appearance of pores and shine.",
    ingredients: "Active Ingredients: Titanium Dioxide 0.7%, Zinc Oxide 17%.\nInactive Ingredients: Cyclopentasiloxane, Dimethicone Crosspolymer, Iron Oxides, Wild Butterfly Ginger Root Extract, Silica.",
    benefits: [
      "100% mineral zinc oxide & titanium dioxide formula",
      "Reduces shine and blurs pores with a soft-focus matte finish",
      "Helps protect against UV rays, blue light, and infrared radiation",
      "Sheer, neutral tint blends seamlessly across most skin tones"
    ],
    howToUse: "Apply generously and evenly as the last step in your skincare routine. Wear alone to control shine, or under makeup as a mattifying primer. Reapply every 2 hours."
  },
  {
    id: "skin-tint",
    name: "Dopahr Protec(tint) Skin Tint SPF 50",
    tagline: "Hydrating skin tint that protects and perfects.",
    price: 44.00,
    rating: 4.8,
    reviewsCount: 890,
    type: "Makeup",
    category: "Face & Lip",
    spf: 50,
    isBestseller: false,
    isNew: true,
    isMineral: true,
    image: "assets/images/glowscreen.jpg",
    description: "Dopahr Protec(tint) Skin Tint SPF 50 is a lightweight, hydrating skin tint that offers light, buildable coverage while protecting skin with broad-spectrum SPF 50 mineral protection. Infused with ectoin and hyaluronic acid, it strengthens the skin barrier and keeps skin plump.",
    ingredients: "Active Ingredients: Zinc Oxide 12%.\nInactive Ingredients: Water, Squalane, Ectoin, Hyaluronic Acid, Coco-Caprylate, Glycerin, Iron Oxides, Centella Asiatica Extract.",
    benefits: [
      "Light, buildable coverage with a natural finish",
      "100% mineral SPF 50 broad spectrum protection",
      "Infused with barrier-boosting Ectoin and Hyaluronic Acid",
      "Breathable, non-comedogenic formula that won't clog pores"
    ],
    howToUse: "Shake well. Dispense a few drops onto fingertips or sponge and blend onto face. Layer for more coverage. Reapply at least every 2 hours."
  },
  {
    id: "sheerscreen",
    name: "Dopahr Sheerscreen SPF 30",
    tagline: "Ultra-sheer, weightless mineral face lotion.",
    price: 38.00,
    rating: 4.7,
    reviewsCount: 420,
    type: "Mineral",
    category: "Face & Lip",
    spf: 30,
    isBestseller: false,
    isNew: true,
    isMineral: true,
    image: "assets/images/clear_spf.jpg",
    description: "Dopahr Sheerscreen SPF 30 is a 100% mineral, ultra-sheer sunscreen lotion that delivers lightweight UV protection with a satin finish. Formulated with aloe vera and squalane, it locks in hydration and calms sensitive skin without leaving a chalky residue.",
    ingredients: "Active Ingredients: Zinc Oxide 15%.\nInactive Ingredients: Aloe Barbadensis Leaf Juice, Squalane, Glycerin, Coconut Alkanes, Shea Butter, Vitamin E.",
    benefits: [
      "100% mineral, non-nano Zinc Oxide formula",
      "Ultra-sheer, satin finish that absorbs completely",
      "Soothes and hydrates sensitive skin with Aloe Vera",
      "Dermatologist tested and fragrance-free"
    ],
    howToUse: "Apply generously and evenly as the last step in your skincare routine. Wear daily alone or under makeup. Reapply every 2 hours."
  },
  {
    id: "glow-stick",
    name: "Dopahr Glow Stick SPF 50",
    tagline: "Portable dry-oil sunscreen stick for a glowing highlight.",
    price: 26.00,
    rating: 4.8,
    reviewsCount: 650,
    type: "Stick",
    category: "Face & Lip",
    spf: 50,
    isBestseller: true,
    isNew: false,
    isMineral: false,
    image: "assets/images/tinted_spf.jpg",
    description: "Dopahr Glow Stick SPF 50 is a travel-friendly, dry-oil sunscreen stick that glides on smoothly to deliver broad-spectrum protection and a luminous, dewy highlight. Use it on your cheekbones, shoulders, and collarbones for a healthy sun-kissed glow without any greasy residue.",
    ingredients: "Active Ingredients: Avobenzone 3%, Homosalate 10%, Octisalate 5%, Octocrylene 10%.\nInactive Ingredients: Caprylic/Capric Triglyceride, Dibutyl Lauroyl Glutamide, Meadowfoam Seed Oil, Tocopherol (Vitamin E).",
    benefits: [
      "Travel-friendly stick for easy on-the-go reapplication",
      "Delivers a gorgeous, translucent dewy highlight",
      "Dry-oil formula absorbs instantly without greasy feel",
      "Perfect for face, lips, shoulders, and collarbones"
    ],
    howToUse: "Glide directly onto face, lips, and body before sun exposure. Swipe over cheekbones or shoulders for an instant glow highlight. Reapply every 2 hours."
  },
  {
    id: "play-gel",
    name: "Dopahr PLAY 100% Mineral Lotion SPF 30",
    tagline: "Water-resistant mineral sunscreen for active days.",
    price: 36.00,
    rating: 4.6,
    reviewsCount: 310,
    type: "Mineral",
    category: "Body",
    spf: 30,
    isBestseller: false,
    isNew: false,
    isMineral: true,
    image: "assets/images/play_lotion.jpg",
    description: "Dopahr PLAY 100% Mineral Lotion SPF 30 is a zinc oxide sunscreen designed specifically for sports and active outdoor play. This sweat- and water-resistant lotion absorbs quickly with minimal whitening and features antioxidant-rich pomegranate extract to nourish skin under peak UV exposure.",
    ingredients: "Active Ingredients: Zinc Oxide 16%.\nInactive Ingredients: Pomegranate Extract, Caprylic/Capric Triglyceride, Water, Sunflower Seed Oil, Glycerin, Silica.",
    benefits: [
      "100% mineral active defense for face and body",
      "Up to 80 minutes sweat and water resistance",
      "Enriched with antioxidant Pomegranate Extract",
      "Fast-absorbing formula designed for sports and play"
    ],
    howToUse: "Apply generously to face and body 15 minutes before activity. Reapply after 80 minutes of swimming or sweating, immediately after towel drying, and at least every 2 hours."
  },
  {
    id: "lip-shield",
    name: "Dopahr Lip Shield SPF 30 Trio",
    tagline: "Hydrating lip balms in Mint, Coconut & Strawberry.",
    price: 18.00,
    rating: 4.8,
    reviewsCount: 520,
    type: "Face & Lip",
    category: "Face & Lip",
    spf: 30,
    isBestseller: false,
    isNew: true,
    isMineral: false,
    image: "assets/images/glowscreen.jpg",
    description: "Dopahr Lip Shield SPF 30 Trio is a set of three deeply hydrating, moisture-locking lip balms flavored with Mint, Coconut, and Strawberry. Each balm protects delicate lips from UV damage while soothing dryness with shea butter, coconut oil, and sunflower seed oil.",
    ingredients: "Active Ingredients: Avobenzone 3%, Homosalate 10%, Octisalate 5%, Octocrylene 10%.\nInactive Ingredients: Beeswax, Shea Butter, Coconut Oil, Sunflower Seed Oil, Mint Extract, Coconut Flavour, Strawberry Extract.",
    benefits: [
      "Protects lips from sunburn and environmental chapping",
      "Three delicious flavors: Mint, Coconut, and Strawberry",
      "Deeply nourishes with Shea Butter & Coconut Oil",
      "Glide-on clear formula with a subtle satin finish"
    ],
    howToUse: "Apply to lips generously 15 minutes before sun exposure. Reapply frequently to maintain hydration and sun protection, especially after eating or drinking."
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = products;
}
