const products = [
  {
    id: "unseen",
    name: "Elevora Apex Smartphone 5G",
    tagline: "Ultimate power, boundary-pushing display.",
    price: 899.00,
    rating: 4.8,
    reviewsCount: 1240,
    type: "Phones",
    category: "Mobiles & Audio",
    spf: 2,
    isBestseller: true,
    isNew: false,
    isMineral: false,
    image: "assets/images/smartphone.jpg",
    description: "Elevora Apex Smartphone 5G features a gorgeous 120Hz LTPO display, professional-grade triple camera system, and the lightning-fast Apex Core Gen 2 processor. Engineered for extreme multitasking, seamless connectivity, and stellar battery efficiency.",
    ingredients: "Display: 6.7-inch QHD+ AMOLED; Processor: Apex Core Gen 2; Battery: 5000mAh; RAM: 12GB; Storage: 256GB.",
    benefits: [
      "Pro-grade triple camera array with optical zoom",
      "Dynamic 120Hz AMOLED display for smooth visuals",
      "Next-gen processor handles gaming and productivity",
      "IP68 water and dust resistance for daily security"
    ],
    howToUse: "Power on and follow on-screen guides to transfer data. Keep software updated. Supports 45W fast charging."
  },
  {
    id: "glow",
    name: "Elevora SoundFlow Headphones",
    tagline: "Pure acoustic bliss, zero distractions.",
    price: 299.00,
    rating: 4.7,
    reviewsCount: 980,
    type: "Audio",
    category: "Mobiles & Audio",
    spf: 1,
    isBestseller: true,
    isNew: true,
    isMineral: false,
    image: "assets/images/headphones.jpg",
    description: "Elevora SoundFlow Wireless Headphones offer top-tier Active Noise Cancellation (ANC), studio-quality spatial audio, and high-fidelity custom drivers. Experience premium comfort with plush memory foam earcups and up to 40 hours of battery life.",
    ingredients: "Driver size: 40mm; Bluetooth: 5.3; Battery: Up to 40 hours (ANC on); Connection: Wireless / 3.5mm jack.",
    benefits: [
      "Hybrid Active Noise Cancellation filters ambient noise",
      "High-fidelity spatial audio for immersive theater sound",
      "Ergonomic memory foam cushions for all-day comfort",
      "Fast charging: 10 mins gives 5 hours playback"
    ],
    howToUse: "Turn on bluetooth pairing, connect to your phone. Adjust ANC settings using the ear cup controls."
  },
  {
    id: "play-lotion",
    name: "Elevora ChronoFit Smartwatch",
    tagline: "Track your health, elevate your style.",
    price: 249.00,
    rating: 4.9,
    reviewsCount: 2150,
    type: "Wearables",
    category: "Laptops & Wearables",
    spf: 2,
    isBestseller: true,
    isNew: false,
    isMineral: false,
    image: "assets/images/smartwatch.jpg",
    description: "Elevora ChronoFit Smartwatch is your ultimate fitness partner and health monitor. Tracks heart rate, blood oxygen, sleep quality, and active stress levels. Housed in a lightweight aluminum body with a high-res customizable AMOLED screen.",
    ingredients: "Screen: 1.43-inch AMOLED; Sensors: PPG Heart Rate, SpO2, Accelerometer; Connectivity: GPS, Bluetooth.",
    benefits: [
      "Continuous heart rate and advanced health tracking",
      "Water-resistant up to 50 meters for swimming",
      "Customizable dials and premium silicone sport band",
      "Up to 7 days battery life on a single charge"
    ],
    howToUse: "Install Elevora Fit App on your phone, pair device via Bluetooth. Synchronize goals."
  },
  {
    id: "body-mist",
    name: "Elevora WaveBlast Speaker",
    tagline: "Waterproof, powerful, and ready to party.",
    price: 129.00,
    rating: 4.6,
    reviewsCount: 730,
    type: "Audio",
    category: "Mobiles & Audio",
    spf: 1,
    isBestseller: true,
    isNew: false,
    isMineral: false,
    image: "assets/images/speaker.jpg",
    description: "Elevora WaveBlast is a portable outdoor Bluetooth speaker delivering massive 360-degree sound and deep bass. IPX7 waterproof rating ensures it handles poolside splashes easily. Dynamic RGB light show pulses to your music beat.",
    ingredients: "Power Output: 30W; Waterproofing: IPX7; Playtime: Up to 15 hours; Lights: 4 RGB modes.",
    benefits: [
      "Room-filling 360-degree sound with deep passive radiators",
      "IPX7 fully waterproof construction for beach and pool",
      "15 hours playtime with fast USB-C recharging",
      "Integrated multi-color LED visual light show"
    ],
    howToUse: "Press and hold power, enable Bluetooth pairing on your device. Connect and stream your playlist."
  },
  {
    id: "mattescreen",
    name: "Elevora ClickMaster Keyboard",
    tagline: "Tactile keypresses, customized RGB comfort.",
    price: 149.00,
    rating: 4.5,
    reviewsCount: 540,
    type: "Accessories",
    category: "Laptops & Wearables",
    spf: 1,
    isBestseller: false,
    isNew: true,
    isMineral: true,
    image: "assets/images/keyboard.jpg",
    description: "Elevora ClickMaster features premium tactile brown mechanical switches, custom double-shot PBT keycaps, and multi-zone customizable RGB backlighting. Sleek aluminum top-plate and detachable wrist rest provide comfortable typing.",
    ingredients: "Key Switch: Tactile Mechanical Brown; Keycaps: Double-shot PBT; Connection: Wired USB-C; Layout: Full Size.",
    benefits: [
      "Tactile mechanical switches for satisfying responsive typing",
      "Vibrant custom RGB backlighting with dynamic profiles",
      "Heavy-duty aluminum alloy top panel for durable builds",
      "Ergonomic layout with removable magnetic wrist rest"
    ],
    howToUse: "Plug in the USB-C cable to your computer. Download key mapper software to customize RGB lighting."
  },
  {
    id: "skin-tint",
    name: "Elevora CineVue 4K Monitor",
    tagline: "Stunning color accuracy, immersive curved screen.",
    price: 449.00,
    rating: 4.8,
    reviewsCount: 890,
    type: "Computers",
    category: "Laptops & Wearables",
    spf: 3,
    isBestseller: false,
    isNew: true,
    isMineral: true,
    image: "assets/images/monitor.jpg",
    description: "Elevora CineVue is a 32-inch curved 4K monitor designed for designers and gamers. Features HDR10 support, 99% sRGB color coverage, and built-in stereo speakers. Curved display reduces eye strain.",
    ingredients: "Resolution: 3840 x 2160 (4K); Panel: IPS Curved; Refresh Rate: 60Hz; Ports: 2x HDMI, 1x DP, USB Hub.",
    benefits: [
      "Crisp 4K UHD resolution with rich HDR10 detailing",
      "Curved screen provides panoramic field of view",
      "High color accuracy (99% sRGB) for photo and video work",
      "Built-in dual speakers and multi-port hub connectivity"
    ],
    howToUse: "Assemble base, connect to power, plug in HDMI/DisplayPort cable to your device. Adjust height/tilt."
  },
  {
    id: "sheerscreen",
    name: "Elevora AirBook Slim Laptop",
    tagline: "Featherlight design, powerhouse speed.",
    price: 999.00,
    rating: 4.7,
    reviewsCount: 420,
    type: "Computers",
    category: "Laptops & Wearables",
    spf: 2,
    isBestseller: false,
    isNew: true,
    isMineral: true,
    image: "assets/images/laptop.jpg",
    description: "Elevora AirBook Slim is a beautifully thin and light laptop built for on-the-go professionals. Featuring a crisp 14-inch IPS display, next-gen Intel processor, and long battery life. Silent fanless design.",
    ingredients: "Processor: Intel i5 Quad-Core; RAM: 16GB; Storage: 512GB NVMe SSD; Screen: 14\" IPS FHD.",
    benefits: [
      "Ultra-thin 0.5-inch metal chassis weighs only 2.7 lbs",
      "Vivid 14-inch display with narrow bezels",
      "Silent fanless design maintains peak cooler performance",
      "Fast-charging battery lasts up to 12 hours"
    ],
    howToUse: "Charge fully, press power button, complete Windows setup wizard. Install your productivity apps."
  },
  {
    id: "glow-stick",
    name: "Elevora PowerDock Charger",
    tagline: "Ultra-compact multi-port fast charger.",
    price: 49.00,
    rating: 4.8,
    reviewsCount: 650,
    type: "Accessories",
    category: "Laptops & Wearables",
    spf: 1,
    isBestseller: true,
    isNew: false,
    isMineral: false,
    image: "assets/images/charger.jpg",
    description: "Elevora PowerDock uses Gallium Nitride (GaN) technology to deliver massive 100W power output in a compact size. Charge up to 3 devices simultaneously with 2x USB-C ports and 1x USB-A port.",
    ingredients: "Max Power: 100W; Tech: GaN V3; Ports: 2x USB-C PD, 1x USB-A QC; Weight: 150g.",
    benefits: [
      "Advanced GaN tech makes it 40% smaller than average chargers",
      "Max 100W power delivery fast-charges laptops and phones",
      "Three output ports allow simultaneous multi-charging",
      "Advanced cooling and device overcharge protection"
    ],
    howToUse: "Plug into wall outlet, connect charging cables from the ports to your devices."
  },
  {
    id: "play-gel",
    name: "Elevora Pods Pro Earbuds",
    tagline: "True wireless freedom, rich active sound.",
    price: 179.00,
    rating: 4.6,
    reviewsCount: 310,
    type: "Audio",
    category: "Mobiles & Audio",
    spf: 1,
    isBestseller: false,
    isNew: false,
    isMineral: true,
    image: "assets/images/earbuds.jpg",
    description: "Elevora Pods Pro deliver premium audio clarity with active noise-canceling technology. In-ear fit with three soft silicone tips ensures secure, comfortable wear. Sweat and water-resistant for workouts.",
    ingredients: "ANC depth: -35dB; Bluetooth: 5.2; Battery: 6 hrs (buds) + 24 hrs (case); Water rating: IPX4.",
    benefits: [
      "Smart Active Noise Cancellation blocks outside noise",
      "Sweat and splashproof (IPX4) for intensive workouts",
      "Compact case supports wireless and USB-C fast charging",
      "Touch controls manage music, calls, and voice assistant"
    ],
    howToUse: "Remove earbuds from case, pair via Bluetooth. Double tap earbud to play/pause or toggle ANC."
  },
  {
    id: "lip-shield",
    name: "Elevora Focus DSLR Camera",
    tagline: "Capture every detail, frame your memories.",
    price: 699.00,
    rating: 4.8,
    reviewsCount: 520,
    type: "Cameras",
    category: "Laptops & Wearables",
    spf: 2,
    isBestseller: false,
    isNew: true,
    isMineral: false,
    image: "assets/images/camera.jpg",
    description: "Elevora Focus DSLR Camera lets you shoot high-resolution images and cinematic 1080p video. Comes with a versatile 18-55mm lens kit, intuitive touchscreen interface, and built-in Wi-Fi.",
    ingredients: "Sensor: 24.2 MP APS-C; Video: 1080p @ 60fps; Screen: 3.0\" Tilt LCD; Lens: 18-55mm IS Kit.",
    benefits: [
      "High-res APS-C sensor captures rich color and detail",
      "Fast autofocus system tracks moving subjects easily",
      "Vibrant tiltable LCD touchscreen simplifies low angles",
      "Built-in Wi-Fi and Bluetooth connects directly to phones"
    ],
    howToUse: "Insert SD card and battery, attach lens, switch dial to Auto or Manual, frame, and press shutter button."
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = products;
}
